"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogTitle,
} from "@/components/ui/dialog";
import { Copy, FileDown, FileText, Linkedin, BookOpen, Share2 } from "lucide-react";
import { cn } from "@/lib/utils";

type RepoShareDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  repoName: string;
  shareContent?: string;
  shareUrl?: string;
  className?: string;
};

const OPTIONS = [
  { id: "link", label: "Copy link", icon: Copy },
  { id: "markdown", label: "Export markdown", icon: FileDown },
  { id: "pdf", label: "Export PDF", icon: FileText },
  { id: "linkedin", label: "Post to LinkedIn", icon: Linkedin },
  { id: "medium", label: "Post to Medium", icon: BookOpen },
  { id: "twitter", label: "Post to X (Twitter)", icon: Share2 },
] as const;

export function RepoShareDialog({
  open,
  onOpenChange,
  repoName,
  shareContent = "",
  shareUrl = typeof window !== "undefined" ? window.location.href : "",
  className,
}: RepoShareDialogProps) {
  const [copied, setCopied] = useState<string | null>(null);

  const handleCopyLink = async () => {
    await navigator.clipboard.writeText(shareUrl);
    setCopied("link");
    setTimeout(() => setCopied(null), 2000);
  };

  const handleExportMarkdown = () => {
    const blob = new Blob([shareContent || `# ${repoName}\n\nGenerated by RepoLens AI.`], {
      type: "text/markdown",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${repoName.replace(/\//g, "-")}-repolens.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent title="Share" className={cn("sm:max-w-md", className)}>
        <div className="border-b border-border px-6 pt-6 pb-2">
          <DialogTitle className="text-lg font-semibold">Share</DialogTitle>
        </div>
        <div className="space-y-4 px-6 pt-4 pb-6">
          <div className="rounded-lg border border-border bg-muted/30 p-3">
            <p className="text-xs font-medium text-muted-foreground">Preview</p>
            <p className="mt-1 text-sm font-semibold text-foreground">RepoLens Analysis</p>
            <p className="mt-0.5 text-xs text-muted-foreground">{repoName}</p>
            <p className="mt-2 line-clamp-3 text-xs text-foreground/90">
              {shareContent?.slice(0, 200) || "Repository overview and key modules."}
              {shareContent && shareContent.length > 200 ? "…" : ""}
            </p>
          </div>
          <div className="space-y-2">
            {OPTIONS.map((opt) => {
            const Icon = opt.icon;
            const isLink = opt.id === "link";
            return (
              <button
                key={opt.id}
                type="button"
                onClick={() => {
                  if (opt.id === "link") handleCopyLink();
                  if (opt.id === "markdown") handleExportMarkdown();
                }}
                className="flex w-full items-center gap-3 rounded-lg border border-border bg-card px-3 py-2.5 text-left text-sm text-foreground transition-colors hover:bg-muted/50"
              >
                <Icon className="h-4 w-4 shrink-0 text-muted-foreground" />
                <span className="flex-1">{opt.label}</span>
                {isLink && copied === "link" && (
                  <span className="text-xs text-primary">Copied</span>
                )}
              </button>
            );
          })}
          </div>
        </div>
        <p className="px-6 pb-6 text-xs text-muted-foreground">
          Share your repository insights. Generated by RepoLens AI.
        </p>
      </DialogContent>
    </Dialog>
  );
}
